services:
      tileserver:
        build:
          context: .
          dockerfile: tileserver/Dockerfile
        container_name: scratchmap_app_tileserver
        ports:
          - "8080:8080"
        volumes:
          - ./tileserver:/data
        
      scratchmapapp.telegrambot:
        image: scratchmapapp.telegrambot
        build:
          context: .
          dockerfile: src/ScratchMapApp.TelegramBot/Dockerfile
        container_name: scratchmap_app
        volumes:
          - ./tileserver/styles:/data
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - TELEGRAM_BOT_TOKEN=YOUR-TOKEN-HERE