# Use an official TileServer GL image as the base image
FROM maptiler/tileserver-gl

# Set the working directory inside the container
WORKDIR /data

# Expose port 8080 for TileServer GL
EXPOSE 8080

# Start TileServer GL with the downloaded MBTiles file
CMD ["--verbose"]
